'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by SpecFlow (http://www.specflow.org/).
'     SpecFlow Version:1.4.0.0
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
#Region "Designer generated code"
Imports TechTalk.SpecFlow

Namespace Rummy.IntegrationTests.Features
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0"),  _
     System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     NUnit.Framework.TestFixtureAttribute(),  _
     NUnit.Framework.DescriptionAttribute("Edit Player")>  _
    Partial Public Class EditPlayerFeature
        
        Private Shared testRunner As TechTalk.SpecFlow.ITestRunner
        
        <NUnit.Framework.TestFixtureSetUpAttribute()>  _
        Public Overridable Sub FeatureSetup()
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner
            Dim featureInfo As TechTalk.SpecFlow.FeatureInfo = New TechTalk.SpecFlow.FeatureInfo(New System.Globalization.CultureInfo("en-US"), "Edit Player", "The Edit Player page allows the user to add new players or edit existing players", GenerationTargetLanguage.VB, CType(Nothing,String()))
            testRunner.OnFeatureStart(featureInfo)
        End Sub
        
        <NUnit.Framework.TestFixtureTearDownAttribute()>  _
        Public Overridable Sub FeatureTearDown()
            testRunner.OnFeatureEnd
            testRunner = Nothing
        End Sub
        
        Public Overridable Sub ScenarioSetup(ByVal scenarioInfo As TechTalk.SpecFlow.ScenarioInfo)
            testRunner.OnScenarioStart(scenarioInfo)
        End Sub
        
        <NUnit.Framework.TearDownAttribute()>  _
        Public Overridable Sub ScenarioTearDown()
            testRunner.OnScenarioEnd
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Add new player")>  _
        Public Overridable Sub AddNewPlayer()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Add new player", CType(Nothing,String()))
            Me.ScenarioSetup(scenarioInfo)
            testRunner.Given("I am on the edit player page")
            testRunner.And("I have entered Eric into the name field")
            testRunner.When("I press the Save button")
            testRunner.Then("Eric will be in the list of players")
            testRunner.CollectScenarioErrors
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Not providing a name value results in error message")>  _
        Public Overridable Sub NotProvidingANameValueResultsInErrorMessage()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Not providing a name value results in error message", CType(Nothing,String()))
            Me.ScenarioSetup(scenarioInfo)
            testRunner.Given("I am on the edit player page")
            testRunner.When("I press the Save button")
            testRunner.Then("I will remain on the edit player page")
            testRunner.And("I will be shown an error message")
            testRunner.CollectScenarioErrors
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Clicking Cancel button does not save player")>  _
        Public Overridable Sub ClickingCancelButtonDoesNotSavePlayer()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Clicking Cancel button does not save player", CType(Nothing,String()))
            Me.ScenarioSetup(scenarioInfo)
            testRunner.Given("I am on the edit player page")
            testRunner.And("I have entered Stan into the name field")
            testRunner.When("I click the Cancel link")
            testRunner.Then("I will be redirected to the Start Game page")
            testRunner.And("Stan will not be in the list of players")
            testRunner.CollectScenarioErrors
        End Sub
    End Class
End Namespace
#End Region
