'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by SpecFlow (http://www.specflow.org/).
'     SpecFlow Version:1.4.0.0
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
#Region "Designer generated code"
Imports TechTalk.SpecFlow

Namespace Rummy.IntegrationTests.Features
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0"),  _
     System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     NUnit.Framework.TestFixtureAttribute(),  _
     NUnit.Framework.DescriptionAttribute("ViewScore")>  _
    Partial Public Class ViewScoreFeature
        
        Private Shared testRunner As TechTalk.SpecFlow.ITestRunner
        
        <NUnit.Framework.TestFixtureSetUpAttribute()>  _
        Public Overridable Sub FeatureSetup()
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner
            Dim featureInfo As TechTalk.SpecFlow.FeatureInfo = New TechTalk.SpecFlow.FeatureInfo(New System.Globalization.CultureInfo("en-US"), "ViewScore", "The main page while a game is in progress.  Displays the current score for each p"& _ 
                    "layer.", GenerationTargetLanguage.VB, CType(Nothing,String()))
            testRunner.OnFeatureStart(featureInfo)
        End Sub
        
        <NUnit.Framework.TestFixtureTearDownAttribute()>  _
        Public Overridable Sub FeatureTearDown()
            testRunner.OnFeatureEnd
            testRunner = Nothing
        End Sub
        
        Public Overridable Sub ScenarioSetup(ByVal scenarioInfo As TechTalk.SpecFlow.ScenarioInfo)
            testRunner.OnScenarioStart(scenarioInfo)
        End Sub
        
        <NUnit.Framework.TearDownAttribute()>  _
        Public Overridable Sub ScenarioTearDown()
            testRunner.OnScenarioEnd
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Display correct score")>  _
        Public Overridable Sub DisplayCorrectScore()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Display correct score", CType(Nothing,String()))
            Me.ScenarioSetup(scenarioInfo)
            testRunner.Given("A game is in progress that requires 500 points to win")
            testRunner.And("Kelly has 40 points and Rob has 100 points")
            testRunner.Then("the score for Kelly should read 40")
            testRunner.And("the score for Rob should read 100")
            testRunner.And("the page should not be in game over mode")
            testRunner.CollectScenarioErrors
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("View Details Link")>  _
        Public Overridable Sub ViewDetailsLink()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("View Details Link", CType(Nothing,String()))
            Me.ScenarioSetup(scenarioInfo)
            testRunner.Given("A game is in progress that requires 500 points to win")
            testRunner.When("I click the view details link")
            testRunner.Then("I should be redirected to the View Score Details page")
            testRunner.CollectScenarioErrors
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Add Score Link")>  _
        Public Overridable Sub AddScoreLink()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Add Score Link", CType(Nothing,String()))
            Me.ScenarioSetup(scenarioInfo)
            testRunner.Given("A game is in progress that requires 500 points to win")
            testRunner.When("I click the add score link")
            testRunner.Then("I should be redirected to the Add Score page")
            testRunner.CollectScenarioErrors
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Game Over")>  _
        Public Overridable Sub GameOver()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Game Over", CType(Nothing,String()))
            Me.ScenarioSetup(scenarioInfo)
            testRunner.Given("A game is in progress that requires 500 points to win")
            testRunner.And("Kelly has 40 points and Rob has 550 points")
            testRunner.Then("the page should be in game over mode")
            testRunner.CollectScenarioErrors
        End Sub
    End Class
End Namespace
#End Region
