
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("660e057d-6b4a-467f-b246-01953bec0484")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class RummyEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new RummyEntities object using the connection string found in the 'RummyEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=RummyEntities", "RummyEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new RummyEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "RummyEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new RummyEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "RummyEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Games() As ObjectSet(Of Game)
        Get
            If (_Games Is Nothing) Then
                _Games = MyBase.CreateObjectSet(Of Game)("Games")
            End If
            Return _Games
        End Get
    End Property

    Private _Games As ObjectSet(Of Game)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property GamePlayers() As ObjectSet(Of GamePlayer)
        Get
            If (_GamePlayers Is Nothing) Then
                _GamePlayers = MyBase.CreateObjectSet(Of GamePlayer)("GamePlayers")
            End If
            Return _GamePlayers
        End Get
    End Property

    Private _GamePlayers As ObjectSet(Of GamePlayer)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property GamePointsByRounds() As ObjectSet(Of GamePointsByRound)
        Get
            If (_GamePointsByRounds Is Nothing) Then
                _GamePointsByRounds = MyBase.CreateObjectSet(Of GamePointsByRound)("GamePointsByRounds")
            End If
            Return _GamePointsByRounds
        End Get
    End Property

    Private _GamePointsByRounds As ObjectSet(Of GamePointsByRound)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Players() As ObjectSet(Of Player)
        Get
            If (_Players Is Nothing) Then
                _Players = MyBase.CreateObjectSet(Of Player)("Players")
            End If
            Return _Players
        End Get
    End Property

    Private _Players As ObjectSet(Of Player)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Games EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToGames(ByVal game As Game)
        MyBase.AddObject("Games", game)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the GamePlayers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToGamePlayers(ByVal gamePlayer As GamePlayer)
        MyBase.AddObject("GamePlayers", gamePlayer)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the GamePointsByRounds EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToGamePointsByRounds(ByVal gamePointsByRound As GamePointsByRound)
        MyBase.AddObject("GamePointsByRounds", gamePointsByRound)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Players EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToPlayers(ByVal player As Player)
        MyBase.AddObject("Players", player)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Rummy", Name:="Game")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Game
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Game object.
    ''' </summary>
    ''' <param name="gameId">Initial value of the GameId property.</param>
    ''' <param name="playedOn">Initial value of the PlayedOn property.</param>
    ''' <param name="statusString">Initial value of the StatusString property.</param>
    ''' <param name="requiredScoreToWin">Initial value of the RequiredScoreToWin property.</param>
    Public Shared Function CreateGame(gameId As Global.System.Int32, playedOn As Global.System.DateTime, statusString As Global.System.String, requiredScoreToWin As Global.System.Int32) As Game
        Dim game as Game = New Game
        game.GameId = gameId
        game.PlayedOn = playedOn
        game.StatusString = statusString
        game.RequiredScoreToWin = requiredScoreToWin
        Return game
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property GameId() As Global.System.Int32
        Get
            Return _GameId
        End Get
        Set
            If (_GameId <> Value) Then
                OnGameIdChanging(value)
                ReportPropertyChanging("GameId")
                _GameId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("GameId")
                OnGameIdChanged()
            End If
        End Set
    End Property

    Private _GameId As Global.System.Int32
    Private Partial Sub OnGameIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnGameIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PlayedOn() As Global.System.DateTime
        Get
            Return _PlayedOn
        End Get
        Set
            OnPlayedOnChanging(value)
            ReportPropertyChanging("PlayedOn")
            _PlayedOn = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PlayedOn")
            OnPlayedOnChanged()
        End Set
    End Property

    Private _PlayedOn As Global.System.DateTime
    Private Partial Sub OnPlayedOnChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnPlayedOnChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StatusString() As Global.System.String
        Get
            Return _StatusString
        End Get
        Set
            OnStatusStringChanging(value)
            ReportPropertyChanging("StatusString")
            _StatusString = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("StatusString")
            OnStatusStringChanged()
        End Set
    End Property

    Private _StatusString As Global.System.String
    Private Partial Sub OnStatusStringChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStatusStringChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RequiredScoreToWin() As Global.System.Int32
        Get
            Return _RequiredScoreToWin
        End Get
        Set
            OnRequiredScoreToWinChanging(value)
            ReportPropertyChanging("RequiredScoreToWin")
            _RequiredScoreToWin = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("RequiredScoreToWin")
            OnRequiredScoreToWinChanged()
        End Set
    End Property

    Private _RequiredScoreToWin As Global.System.Int32
    Private Partial Sub OnRequiredScoreToWinChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnRequiredScoreToWinChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Rummy", Name:="GamePlayer")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class GamePlayer
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new GamePlayer object.
    ''' </summary>
    ''' <param name="gameId">Initial value of the GameId property.</param>
    ''' <param name="playerId">Initial value of the PlayerId property.</param>
    ''' <param name="isWinner">Initial value of the IsWinner property.</param>
    ''' <param name="points">Initial value of the Points property.</param>
    Public Shared Function CreateGamePlayer(gameId As Global.System.Int32, playerId As Global.System.Int32, isWinner As Global.System.String, points As Global.System.Int32) As GamePlayer
        Dim gamePlayer as GamePlayer = New GamePlayer
        gamePlayer.GameId = gameId
        gamePlayer.PlayerId = playerId
        gamePlayer.IsWinner = isWinner
        gamePlayer.Points = points
        Return gamePlayer
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property GameId() As Global.System.Int32
        Get
            Return _GameId
        End Get
        Set
            If (_GameId <> Value) Then
                OnGameIdChanging(value)
                ReportPropertyChanging("GameId")
                _GameId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("GameId")
                OnGameIdChanged()
            End If
        End Set
    End Property

    Private _GameId As Global.System.Int32
    Private Partial Sub OnGameIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnGameIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PlayerId() As Global.System.Int32
        Get
            Return _PlayerId
        End Get
        Set
            If (_PlayerId <> Value) Then
                OnPlayerIdChanging(value)
                ReportPropertyChanging("PlayerId")
                _PlayerId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("PlayerId")
                OnPlayerIdChanged()
            End If
        End Set
    End Property

    Private _PlayerId As Global.System.Int32
    Private Partial Sub OnPlayerIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnPlayerIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IsWinner() As Global.System.String
        Get
            Return _IsWinner
        End Get
        Set
            OnIsWinnerChanging(value)
            ReportPropertyChanging("IsWinner")
            _IsWinner = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("IsWinner")
            OnIsWinnerChanged()
        End Set
    End Property

    Private _IsWinner As Global.System.String
    Private Partial Sub OnIsWinnerChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIsWinnerChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Points() As Global.System.Int32
        Get
            Return _Points
        End Get
        Set
            OnPointsChanging(value)
            ReportPropertyChanging("Points")
            _Points = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Points")
            OnPointsChanged()
        End Set
    End Property

    Private _Points As Global.System.Int32
    Private Partial Sub OnPointsChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnPointsChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Rummy", Name:="GamePointsByRound")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class GamePointsByRound
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new GamePointsByRound object.
    ''' </summary>
    ''' <param name="gameId">Initial value of the GameId property.</param>
    ''' <param name="playerId">Initial value of the PlayerId property.</param>
    ''' <param name="roundNumber">Initial value of the RoundNumber property.</param>
    ''' <param name="points">Initial value of the Points property.</param>
    Public Shared Function CreateGamePointsByRound(gameId As Global.System.Int32, playerId As Global.System.Int32, roundNumber As Global.System.Int32, points As Global.System.Int32) As GamePointsByRound
        Dim gamePointsByRound as GamePointsByRound = New GamePointsByRound
        gamePointsByRound.GameId = gameId
        gamePointsByRound.PlayerId = playerId
        gamePointsByRound.RoundNumber = roundNumber
        gamePointsByRound.Points = points
        Return gamePointsByRound
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property GameId() As Global.System.Int32
        Get
            Return _GameId
        End Get
        Set
            If (_GameId <> Value) Then
                OnGameIdChanging(value)
                ReportPropertyChanging("GameId")
                _GameId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("GameId")
                OnGameIdChanged()
            End If
        End Set
    End Property

    Private _GameId As Global.System.Int32
    Private Partial Sub OnGameIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnGameIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PlayerId() As Global.System.Int32
        Get
            Return _PlayerId
        End Get
        Set
            If (_PlayerId <> Value) Then
                OnPlayerIdChanging(value)
                ReportPropertyChanging("PlayerId")
                _PlayerId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("PlayerId")
                OnPlayerIdChanged()
            End If
        End Set
    End Property

    Private _PlayerId As Global.System.Int32
    Private Partial Sub OnPlayerIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnPlayerIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RoundNumber() As Global.System.Int32
        Get
            Return _RoundNumber
        End Get
        Set
            If (_RoundNumber <> Value) Then
                OnRoundNumberChanging(value)
                ReportPropertyChanging("RoundNumber")
                _RoundNumber = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("RoundNumber")
                OnRoundNumberChanged()
            End If
        End Set
    End Property

    Private _RoundNumber As Global.System.Int32
    Private Partial Sub OnRoundNumberChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnRoundNumberChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Points() As Global.System.Int32
        Get
            Return _Points
        End Get
        Set
            OnPointsChanging(value)
            ReportPropertyChanging("Points")
            _Points = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Points")
            OnPointsChanged()
        End Set
    End Property

    Private _Points As Global.System.Int32
    Private Partial Sub OnPointsChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnPointsChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Rummy", Name:="Player")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Player
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Player object.
    ''' </summary>
    ''' <param name="playerId">Initial value of the PlayerId property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    Public Shared Function CreatePlayer(playerId As Global.System.Int32, name As Global.System.String) As Player
        Dim player as Player = New Player
        player.PlayerId = playerId
        player.Name = name
        Return player
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PlayerId() As Global.System.Int32
        Get
            Return _PlayerId
        End Get
        Set
            If (_PlayerId <> Value) Then
                OnPlayerIdChanging(value)
                ReportPropertyChanging("PlayerId")
                _PlayerId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("PlayerId")
                OnPlayerIdChanged()
            End If
        End Set
    End Property

    Private _PlayerId As Global.System.Int32
    Private Partial Sub OnPlayerIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnPlayerIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    #End Region
End Class

#End Region

